### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by kreafik** [boidushya/boidushya.com#8]
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
  
  
  git clone - > npm install after that i got this err

**Comment by boidushya** [comment]
This error is caused by OpenSSL Legacy Provider, you can find out how to configure it for your system from [here](https://stackoverflow.com/a/69746937/18253276) (if youre using powershell, do [this](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported#comment124897641_69746937) instead 

TL;DR

Shell: `export NODE_OPTIONS=--openssl-legacy-provider`
Powershell: `$env:NODE_OPTIONS="--openssl-legacy-provider"`

**Comment by kreafik** [comment]
"scripts": {
		"start": "craco start --openssl-legacy-provider",
		"build": "craco build",
		"test": "craco test",
		"eject": "react-scripts eject"
	}
	
	
	
On localhost, works well now. Thanks. ^^
